### ISSUE TITLE
last steps 

### ISSUE THREAD

**Issue by TomFixemer** [SeGePae/segepaed#13]
@LinguList 
Hi Mattis, 
I have updated the run numbers and uploaded the necessary documents as with the last pull request. 
I am not sure if I have to take a another step for the transmission. 
if you have time you can check it.
thank you. 
best, tom

**Comment by LinguList** [comment]
I will try to look into that on June 24, but cannot promise to manage to 
do this completely.

**Comment by LinguList** [comment]
All done.

**Comment by TomFixemer** [comment]
thank you so much Mattis for your Support!
