### ISSUE TITLE
Hauptseite neu erstellen

### ISSUE THREAD

**Issue by IngaMList** [SeGePae/segepaed#3]
- FH-Adresse im Imprint
- Willkommensseite // Startseite
- Titel anpassen
- Diese Seite dient dann englischem und deutschem Monitoring
- Tabs englisches und deutsches Monitoring
- Mirja informieren: Verlinkung zu dieser Seite bei Homepage einfügen

**Comment by IngaMList** [comment]
Fürs Imprint: https://www.fh-kiel.de/index.php?id=3712

**Comment by IngaMList** [comment]
Angepasster Titel: Sexualisierte Gewalt gegen Kinder und Jugendliche in pädagogischen Kontexten: Forschungsliteratur-Monitoring

**Comment by IngaMList** [comment]
Willkommensseite: 
Im Rahmen des BMBF-geförderten Forschungsnetzwerks "Sexualisierte Gewalt gegen Kinder und Jugendliche in pädagogischen Kontexten" werden zwei verschiedene Monitorings zur Einordnung relevanter Forschungsliteratur durchgeführt. Für die Literaturdatenbank zur englischsprachigen Fachliteratur klicken Sie bitte auf den Tab "Englischsprachiges Monitoring", für die Datenbank deutschsprachiger Fachliteratur auf den Tab "Deutschsprachiges Monitoring".

**Comment by IngaMList** [comment]
Die anderen Seiten passe ich wie besprochen direkt unter Static an.

**Comment by IngaMList** [comment]
Korrektur: Das Logo vom BMBF kann drin bleiben (wäre möglich "gefördert vom" hinzuzufügen?). CAU soll raus und NICHT durch FH ersetzt werden. Imprint hingegen wie o.g.

**Comment by LinguList** [comment]
also, wenn das eine logo raussoll, ist das dämlich, das ist doch nicht ausgewogen. Ich lasse erst mal beide drin, sonst eben keins.

**Comment by LinguList** [comment]
oder ein leeres bild, aber es wäre gut was zur ästhetischen balance da zu haben....

**Comment by IngaMList** [comment]
Alles erledigt. 
Wenn schnell möglich, BMBF-Logo(s) ersetzen durch dieses hier: [https://www.uni-giessen.de/fbz/zentren/zfbk/didaktik/lehrinnovationsfonds/downloads/logos/BMBF-CMYK-Gef-L-300dpi/image_view_fullscreen]

**Comment by LinguList** [comment]
okay, wurde gemacht nun.

**Comment by IngaMList** [comment]
Ja, super!
