### ISSUE TITLE
static/cats.html

### ISSUE THREAD

**Issue by IngaMList** [SeGePae/segepaed#6]
Frage an Mattis: Oder soll ich hier direkt die Kategorien einfügen und korrigieren? Hilft dir das was?

**Comment by IngaMList** [comment]
Oder besser hier: segepaed/kats.html

**Comment by LinguList** [comment]
Kannst du probieren! Aber schau ob's zu aufwendig ist. Wobei im Prinzip ist das auch eine Art Qualitätscheck, falls du dich vertippt hast.

**Comment by IngaMList** [comment]
Hab jetzt alles unter static/cats geändert. Ich hoffe sehr, dass es richtig ist! Die Stellen, an denen ich besonders unschlüssig war, habe ich noch mal unten angemerkt.

**Comment by IngaMList** [comment]
Schicke zur Sicherheit die Kategorien noch mal per Worddatei an dich.

**Comment by IngaMList** [comment]
In Sec3 geändert wie telefonisch besprochen.
