### ISSUE TITLE
merch

### ISSUE THREAD

**Issue by TomFixemer** [SeGePae/segepaed#9]
@LinguList 
sorry about pressing the merch button - when I read about GitHub the 'merch' was all the time important - but I thought you check all the changes before releasing.

**Comment by LinguList** [comment]
It is just the procedure, but it is okay. I check this anyway, and I can 
revrt the changes. No worries.

**Comment by LinguList** [comment]
@tomfixemer, can you now please also upload the new bibtex file?

**Comment by LinguList** [comment]
This time just merge, without the pull request, this is fine, just 
inform me once it is uploaded.

**Comment by LinguList** [comment]
So what I need now is just the bibliography to be updated, and the keywords, if I am not mistaken. data/keywords.tsv and data/Bibliographie.tsv

**Comment by TomFixemer** [comment]
I get a list from citavi with the keywords?


________________________________
Von: Johann-Mattis List ***@***.***>
Gesendet: Mittwoch, 31. März 2021 13:39
An: SeGePae/segepaed
Cc: Fixemer, Tom; Mention
Betreff: Re: [SeGePae/segepaed] merch (#9)


So what I need now is just the bibliography to be updated, and the keywords, if I am not mistaken. data/keywords.tsv and data/Bibliographie.tsv

**Comment by LinguList** [comment]
Figured we don't need them, the old list is okay.

**Comment by LinguList** [comment]
The first bibliography is finished (for German). I'd ask you to download the github repository now, unpack it, go to the folder "segepaed" and open the file `index.html` with firefox or chrome or safari, and check if this is okay.

**Comment by LinguList** [comment]
If this is the case, we'll upload to the main page. If there are spelling problems, please correct the sections (as following instructions).

**Comment by LinguList** [comment]
And please also let me know in the English part, once this has been done, so I can update there as well.

**Comment by TomFixemer** [comment]
from my side nothing is changed in the english monitoring - the update only affects the german monitoring

________________________________
Von: Johann-Mattis List ***@***.***>
Gesendet: Mittwoch, 31. März 2021 15:40:49
An: SeGePae/segepaed
Cc: Fixemer, Tom; Mention
Betreff: Re: [SeGePae/segepaed] merch (#9)


And please also let me know in the English part, once this has been done, so I can update there as well.

**Comment by LinguList** [comment]
Okay, so should we put it online then?
